version: '3.8'
services:
  adb_server:
    build: .
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - .:/app
      - /dev/bus/usb:/dev/bus/usb
    command: ["python3", "./app.py"]
    network_mode: "host"
